name: snapchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  camera: ^0.10.5
  cloud_firestore: ^5.6.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutterfire_cli: ^1.0.1  # Moved to dev_dependencies

flutter:
  uses-material-design: true

  assets:
    - assets/male.jpg
    - assets/female.jpg
