// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4I5mYgTDMCrq6cveHx7ofTNczwpGeim0',
    appId: '1:739216038120:web:b6f592f61eca542169d15d',
    messagingSenderId: '739216038120',
    projectId: 'snapchat-clone-d9edb',
    authDomain: 'snapchat-clone-d9edb.firebaseapp.com',
    storageBucket: 'snapchat-clone-d9edb.firebasestorage.app',
    measurementId: 'G-THNP5VE42X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDpD8J2w4tYdY-4-vX8QgV1oDE9XGPJYg',
    appId: '1:739216038120:ios:dbb9ffc754e8a4e769d15d',
    messagingSenderId: '739216038120',
    projectId: 'snapchat-clone-d9edb',
    storageBucket: 'snapchat-clone-d9edb.firebasestorage.app',
    iosBundleId: 'com.example.snapchatclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4I5mYgTDMCrq6cveHx7ofTNczwpGeim0',
    appId: '1:739216038120:web:a907a7fc3a658f0f69d15d',
    messagingSenderId: '739216038120',
    projectId: 'snapchat-clone-d9edb',
    authDomain: 'snapchat-clone-d9edb.firebaseapp.com',
    storageBucket: 'snapchat-clone-d9edb.firebasestorage.app',
    measurementId: 'G-PDJYEXVCK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJu2UNMttqvDuArdair6sMpIqvn9GXYA',
    appId: '1:739216038120:android:8b6a09d446a4a23f69d15d',
    messagingSenderId: '739216038120',
    projectId: 'snapchat-clone-d9edb',
    storageBucket: 'snapchat-clone-d9edb.firebasestorage.app',
  );

}